### PR TITLE
NDRCN-294 Amends

### PR DESCRIPTION
**Pull request by somaraja**

### CODE REVIEW

**Review by lmugnai — COMMENTED** [review]
@somaraja could we have some tests to ensure the correct title is displayed?

**Review by lmugnai — COMMENTED** [review]
@somaraja instead of passing the useranswers object into the view and adding logic, what do you think about doing the useranswers.get in the controller and passing a boolean into the view, for example isImporterJourney?

**Comment by somaraja** [comment]
> @somaraja instead of passing the useranswers object into the view and adding logic, what do you think about doing the useranswers.get in the controller and passing a boolean into the view, for example isImporterJourney?

@lmugnai changes incorporated

**Comment by somaraja** [comment]
> @somaraja could we have some tests to ensure the correct title is displayed?

@lmugnai test cases added

**Review by lmugnai — APPROVED** [review]

**Pull request merged**
